### ISSUE TITLE
error when running make command

### ISSUE THREAD

**Issue by PattinsonNguyen** [facebook/fbthrift#121]
Hi everyone.
I get troubles when running the last command: make; in order to build fbthrift.

![selection_003](https://cloud.githubusercontent.com/assets/13861413/9401644/d6c7dd6c-47fc-11e5-8b8a-7c84e566a9cf.png)

Anyone can help me? Thanks!

**Comment by redwardstern** [comment]
I ran into several issues during the make of version 30.  
Currently I am unable to build, because cpp2 does not have a generator for thrift1.  This means that the command to generate Sas1.thrift fails.

I am not sure if this is the same error as above (it's clipped unfortunately), however adding my observations here:

1.  Build 30.0 fails when running ../../.python-local/[clipped]/main.py  because it can't find the paths to generate:To correct this I added the additional paths to the Makefile in the cpp2 directory: 

'PYTHONPATH=$(PY_LOCAL_PATH):$(PY_LOCAL_PATH)/thrift_py-0.9.0-py3.4.egg/thrift_compiler:$(PY_LOCAL_PATH)/thrift_py-0.9.0-py3.4.egg/thrift_compiler/generate')

2.  Build 30.0 doesn't generate for cpp2.  The Sasl.thrift file is not generated and the  Sasl_constants.cpp file can't be found. I generated these files manually using cpp and then copied them into the cpp2/gen-cpp2 directory

make[5]: Entering directory '/home/rutje/fbthrift/thrift/lib/cpp2'
PYTHONPATH=../../.python-local/lib/python:../../.python-local/lib/python/thrift_py-0.9.0-py3.4.egg/thrift_compiler:../../.python-local/lib/python/thrift_py-0.9.0-py3.4.egg/thrift_compiler/generate /home/rutje/.conda/envs/thesis/bin/python -mthrift_compiler.main --gen cpp2 Sasl.thrift
Argument Error: Language cpp2 not defined.
g++ -DHAVE_CONFIG_H   -fPIC -I../../..  -pthread -I/usr/include  -I../cpp -I../../../../gperftools-2.0.99/src -I/usr/local/include   -std=gnu++0x -MT gen-cpp2/libsaslstubs_a-Sasl_constants.o -MD -MP -MF gen-cpp2/.deps/libsaslstubs_a-Sasl_constants.Tpo -c -o gen-cpp2/libsaslstubs_a-Sasl_constants.o `test -f 'gen-cpp2/Sasl_constants.cpp' || echo './'`gen-cpp2/Sasl_constants.cpp
g++: error: ./gen-cpp2/Sasl_constants.cpp: No such file or directory
g++: fatal error: no input files

Please notify me if we are working with separate issues and I will create a separate bug.  The area seems to be related, based on the attached png.

**Comment by eduardo-elizondo** [comment]
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.
