### ISSUE TITLE
fbthrift based client failed with "unsupported protocol id" error.

### ISSUE THREAD

**Issue by sd24** [facebook/fbthrift#267]
I was trying to come up with “fbthrift” based client. The server is in Apache thrift.

The following code written using “fbthrift”  functionalities fails, and server reports “unsupported protocol id” error.

EventBase base;
std::shared_ptr<TAsyncSocket> socket(TAsyncSocket::newSocket(&base, "127.0.0.1", port));
auto client_channel = HeaderClientChannel::newChannel(socket);
client_channel->useAsHttpClient("127.0.0.1", "/");
client_channel->setProtocolId(apache::thrift::protocol::T_COMPACT_PROTOCOL);
MyThriftServerClient client(std::move(client_channel));
client.future_ping("test").waitVia(&base);

**_The same thrift client code when written with Apache thrift, works as expected._**

ThriftConnection connection;
connection.socket = boost::shared_ptr<TTransport>(new TSocket(host_, port_));
connection.transport = boost::shared_ptr<TTransport>(new THttpClient(host_, port_, "/"));
connection.protocol = boost::shared_ptr<TProtocol>
                               (new TCompactProtocol(connection.transport));
connection.client = boost::shared_ptr<MyThriftServerClient>
                               (new MyThriftServerClient(connection.protocol));
connection.transport->open();

Did any one else faced same problem?

**Comment by yfeldblum** [comment]
The client in the example uses fbthrift header transport - notice specifically the use of `HeaderClientChannel`. This facility does not exist in apache thrift, which is why the apache thrift server code does not understand the message sent by the fbthrift client code.

The client may be downgraded to framed transport with:

```
client_channel->setClientType(THRIFT_FRAMED_DEPRECATED);
```

Note additionally that fbthrift compact protocol and apache thrift compact protocol are mostly similar but are not 100% compatible with each other.
