### ISSUE TITLE
Make error with ubuntu 16.04

### ISSUE THREAD

**Issue by dang123vvk** [facebook/fbthrift#310]
Make error with ubuntu 16.04
[ 93%] Building CXX object thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/transport/core/ThriftClient.cpp.o
[ 93%] Building CXX object thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/transport/core/ThriftClientCallback.cpp.o
[ 94%] Building CXX object thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/util/ScopedServerInterfaceThread.cpp.o
[ 95%] Building CXX object thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/util/ScopedServerThread.cpp.o
[ 95%] Building CXX object thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/__/thrift/gen-cpp2/RpcMetadata_constants.cpp.o
[ 96%] Building CXX object thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/__/thrift/gen-cpp2/RpcMetadata_data.cpp.o
[ 97%] Building CXX object thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/__/thrift/gen-cpp2/RpcMetadata_types.cpp.o
make[2]: *** No rule to make target '../thrift/lib/cpp2/transport/rsocket/gen-cpp2/Config_constants.cpp', needed by 'thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/transport/rsocket/gen-cpp2/Config_constants.cpp.o'.  Stop.
CMakeFiles/Makefile2:749: recipe for target 'thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/all' failed
make[1]: *** [thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zsrinivas** [comment]
same issue

+1

**Comment by calebmarchent** [comment]
Sounds like a missing dependency issue between the generated code `Config_constants.cpp` and the object files compiled from it; I've debugged a couple of these. I shall see if I can reproduce...

**Comment by calebmarchent** [comment]
I have been able to reproduce something similar, but cleaning the directory and explicitly calling `make thriftcpp2` as the first target for evaluation. 

I can see that `../thrift/lib/cpp2/transport/rsocket/gen-cpp2/Config_constants.cpp` is generated by `Config-cpp2-target` which calls the thrift1 compiler; but there is no explicit dependency declared between library `thriftcpp2 (thrift/lib/cpp2/CMakeLists.txt)` and `Config-cpp2-target`; so it is likely that 'luck' means that Config-cpp2-target just happens to be created before thriftcpp2 in most cases.

I have create https://github.com/facebook/fbthrift/pull/314 to fix the issue, @dang123vvk  or @zsrinivas please test with this fix applied and confirm if the issue is resolved?
