### ISSUE TITLE
gcc compiler error, how to fix?

### ISSUE THREAD

**Issue by jonike** [facebook/fbthrift#96]
=Compiler Output=
async/Cpp2Channel.cpp:68:14: error: ‘class folly::wangle::StaticPipeline<folly::IOBufQueue&, std::unique_ptr<folly::IOB
uf>, apache::thrift::TAsyncTransportHandler, folly::wangle::OutputBufferingHandler, apache::thrift::ProtectionHandler, a
pache::thrift::Cpp2Channel>’ has no member named ‘attachTransport’
   pipeline_->attachTransport(transport);
              ^

**Comment by bamos** [comment]
I think this issue is caused by @jsedgwick's commit to facebook/folly that
removes `attachTransport`: https://github.com/facebook/folly/commit/1185881df4c4a6195f5cd99dae703a0ff0a1ec58

I'm not very familiar with the projects, but I'm able to build `fbthrift`
with a version of `folly` before this commit. (Arbitrarily using 38:0, `c923afa`)

**Comment by andrewcox** [comment]
Our projects have breaking changes from time to time, and it seems this is what has happened here. The deps.sh script (mentioned on the README.md for this repo) should pull down & build the correct version of folly, and then it will build fbthrift against that (e.g. for now it pulls v37.0)

**Comment by andrewcox** [comment]
And by "correct version of folly", in this case I only mean the version that works with the latest release of thrift.

**Comment by bamos** [comment]
Thanks @andrewcox - I was using https://github.com/facebook/fblualib/blob/master/install_all.sh, which doesn't use deps.sh from this repo and checks out the master branches of the dependencies - I filed an issue there for this to be corrected.
